
muscles = [ "GM", ...
            "Sol", ...
            "TA2",...
            "GM", ...
            "Sol", ...
            "TA1", ...
            "TA2",...
            "GM", ...
            "Sol", ...
            "TA1", ...
            "TA2",...
            "GM", ...
            "Sol", ...
            "TA1", ...
            "TA2"];

degrees = [ "0",...
            "0",...
            "0",...
            "10",... 
            "10",... 
            "10",... 
            "10",... 
            "20",... 
            "20",... 
            "20",... 
            "20",... 
            "5",...
            "5",...
            "5",...
            "5"];
        
muscle_names = strings(size(muscles));
for i = 1:length(muscles)
   muscle_names(i) = strcat(degrees(i), 'deg_', muscles(i));
end


file_prefix = 'MVC35_';
for i=1:length(muscle_names)
        filepath = strcat(file_prefix, muscle_names(i), '/');
        load(strcat(filepath, 'Markers'))
        figure()
        subplot(3,1,1), plot(Markers.RawData(:,34))
        title(strcat(muscle_names(i)))
        subplot(3,1,2), plot(Markers.RawData(:,35))
        subplot(3,1,3), plot(Markers.RawData(:,36))
end
















